name: Polybot Build Dev

on:
  push:
    branches:
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_output.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        id: set_output
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
          
          img_name=${{ secrets.DOCKERHUB_USERNAME }}/polybot-dev:${{ github.run_number }}
          
          # Export image name as output
          echo "image=$img_name" >> $GITHUB_OUTPUT
          
          # Build and push image
          docker build --push -t $img_name .

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy_dev.yaml
    with:
      image: ${{ needs.Build.outputs.image }}
    secrets:
      EC2_HOST: ${{ secrets.EC2_DEV_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN_DEV }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
