name: Yolo Build Dev

on:
  push:
    branches:
      - dev

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      yolo_image: ${{ steps.set_yolo.outputs.image }}
      consumer_image: ${{ steps.set_consumer.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build YOLO Docker image
        id: set_yolo
        run: |
          yolo_img=${{ secrets.DOCKERHUB_USERNAME }}/yolo-dev:${{ github.run_number }}
          echo "image=$yolo_img" >> $GITHUB_OUTPUT
          docker build --push -t $yolo_img .

      - name: Build Consumer Docker image
        id: set_consumer
        run: |
          consumer_img=${{ secrets.DOCKERHUB_USERNAME }}/yolo-consumer-dev:${{ github.run_number }}
          echo "image=$consumer_img" >> $GITHUB_OUTPUT
          docker build --push -f Dockerfile.consumer -t $consumer_img .

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy_dev.yaml
    with:
      image: ${{ needs.Build.outputs.yolo_image }}
      consumer_image: ${{ needs.Build.outputs.consumer_image }}
    secrets:
      EC2_HOST: ${{ secrets.EC2_DEV_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
      SQS_AWS_REGION: ${{ secrets.SQS_AWS_REGION }}
      QUEUE_URL: ${{ secrets.QUEUE_URL_DEV }}
      POLYBOT_URL: ${{ secrets.POLYBOT_URL_DEV }}
