name: Docker Scout PR Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  docker-scout-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for PR scan
        id: build_image
        run: |
          img_name=${{ secrets.DOCKERHUB_USERNAME }}/polybot:pr-${{ github.run_number }}
          echo "image=$img_name" >> $GITHUB_OUTPUT
          docker buildx build --load -t $img_name .

      - name: Run Docker Scout scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ steps.build_image.outputs.image }}
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on: critical,high
